# Generated by Django 5.2.14 on 2026-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_connector_confluence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='provider',
            field=models.CharField(choices=[('sharepoint', 'SharePoint'), ('google_drive', 'Google Drive'), ('confluence', 'Confluence'), ('dropbox', 'Dropbox')], max_length=40),
        ),
    ]
