# Generated by Django 5.2.14 on 2026-05-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0005_proxiwebthread_proxiwebmessage'),
        ('support', '0002_alter_supportmessage_kind_supportcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=128, unique=True)),
                ('stream_sid', models.CharField(blank=True, max_length=128)),
                ('from_number', models.CharField(blank=True, max_length=64)),
                ('to_number', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=128)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('source_label', models.CharField(default='docstore-voice-agent', max_length=64)),
                ('transcript_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_records', to='support.supportchannel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_records', to='control.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_records', to='control.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
