# Generated by Django 5.2.14 on 2026-05-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_proxiwebthread_proxiwebmessage'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='kind',
            field=models.CharField(choices=[('sms', 'SMS'), ('call_note', 'Call Note'), ('voicemail', 'Voicemail'), ('system', 'System')], default='sms', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('from_number', models.CharField(blank=True, default='', max_length=32)),
                ('to_number', models.CharField(blank=True, default='', max_length=32)),
                ('caller_name', models.CharField(blank=True, default='', max_length=255)),
                ('recording_sid', models.CharField(blank=True, default='', max_length=64)),
                ('recording_url', models.TextField(blank=True, default='')),
                ('transcription_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='support.supportchannel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='support.supportcontact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='support.supportconversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_calls', to='control.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
