# Generated by Django 5.2.14 on 2026-06-02 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0008_alter_externalaccount_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetTransformJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('export_format', models.CharField(choices=[('xlsx', 'XLSX'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('transform_request', models.TextField(blank=True, default='')),
                ('strict_sanitization', models.BooleanField(default=False)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('headers_json', models.JSONField(blank=True, default=list)),
                ('rows_json', models.JSONField(blank=True, default=list)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/spreadsheet_transforms/%Y/%m/%d/')),
                ('error_text', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheet_transform_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheet_transform_jobs', to='control.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheet_transform_jobs', to='control.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'workspace', 'status'], name='reports_spr_tenant__e332bc_idx')],
            },
        ),
    ]
