# Generated by Django 5.2.14 on 2026-05-28 13:24

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_chunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, storage=documents.storage.DocumentStorage(), upload_to='documents/%Y/%m/%d/'),
        ),
    ]
