# Generated by Django 5.2.14 on 2026-08-03 11:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_rename_documents_d_workspa_91d743_idx_documents_d_workspa_466642_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='metadata_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='question_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
