# Generated by Django 5.2.14 on 2026-05-30 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0005_proxiwebthread_proxiwebmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('persona_prompt', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('runtime_mode', models.CharField(choices=[('shared_runner', 'Shared runner'), ('isolated_runner', 'Isolated runner')], default='shared_runner', max_length=32)),
                ('template_name', models.CharField(blank=True, default='', max_length=120)),
                ('template_version', models.CharField(blank=True, default='', max_length=64)),
                ('allowed_tools_json', models.JSONField(blank=True, default=dict)),
                ('response_policy_json', models.JSONField(blank=True, default=dict)),
                ('handoff_policy_json', models.JSONField(blank=True, default=dict)),
                ('logging_policy_json', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_definitions', to='control.workspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_definitions', to='control.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed'), ('deployed', 'Deployed')], default='queued', max_length=20)),
                ('artifact_type', models.CharField(choices=[('config', 'Config'), ('template_bundle', 'Template bundle')], default='config', max_length=32)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=500)),
                ('generated_manifest_json', models.JSONField(blank=True, default=dict)),
                ('build_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_builds_created', to=settings.AUTH_USER_MODEL)),
                ('bot_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='chatbots.chatbotdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('bot_definition', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ChatbotDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_type', models.CharField(blank=True, default='', max_length=64)),
                ('runner_target', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='chatbots.chatbotdefinition')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='chatbots.chatbotbuild')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('dm', 'Direct Message'), ('group', 'Group'), ('channel', 'Channel'), ('thread', 'Thread'), ('meeting', 'Meeting'), ('chat_room', 'Chat Room')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('external_parent_id', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('dm_only', 'DM only'), ('mention_only', 'Mention only'), ('always_on', 'Always on'), ('meeting_assistant', 'Meeting assistant')], default='mention_only', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_endpoints', to='control.workspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_endpoints', to='control.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('zoom_chat', 'Zoom Chat'), ('zoom_meeting', 'Zoom Meeting')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('external_app_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_bot_id', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_status', models.CharField(blank=True, default='', max_length=64)),
                ('credentials_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_integrations', to='control.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('event_type', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='chatbots.chatbotdefinition')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='chatbots.chatbotendpoint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_event_logs', to='control.tenant')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='chatbots.chatbotintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatbotendpoint',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='chatbots.chatbotintegration'),
        ),
        migrations.AddField(
            model_name='chatbotdefinition',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='chatbots.chatbotintegration'),
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('zoom_chat', 'Zoom Chat'), ('zoom_meeting', 'Zoom Meeting')], max_length=32)),
                ('external_conversation_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to='control.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_conversations', to='control.workspace')),
                ('bot_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chatbots.chatbotdefinition')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chatbots.chatbotendpoint')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbots.chatbotintegration')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('system', 'System')], max_length=20)),
                ('external_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('sender_external_id', models.CharField(blank=True, default='', max_length=255)),
                ('sender_label', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('normalized_content_json', models.JSONField(blank=True, default=dict)),
                ('retrieval_metadata_json', models.JSONField(blank=True, default=dict)),
                ('model_metadata_json', models.JSONField(blank=True, default=dict)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbots.chatbotconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotEndpointBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_bindings', to='chatbots.chatbotdefinition')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_bindings', to='chatbots.chatbotendpoint')),
                ('workspace_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_endpoint_bindings', to='control.workspace')),
            ],
            options={
                'ordering': ['bot_definition__name', 'endpoint__display_name'],
                'unique_together': {('bot_definition', 'endpoint')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatbotendpoint',
            unique_together={('integration', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='chatbotdefinition',
            unique_together={('tenant', 'slug')},
        ),
    ]
