# Generated by Django 5.2.14 on 2026-05-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotintegration',
            name='runner_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
