# Generated by Django 5.2.14 on 2026-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_externalaccount_atlassian_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='provider',
            field=models.CharField(choices=[('microsoft', 'Microsoft'), ('google', 'Google'), ('atlassian', 'Atlassian'), ('dropbox', 'Dropbox')], max_length=40),
        ),
    ]
